<?php 

$GLOBALS['porteurMap'] = array(
	//Name			=> directory name on server
// 'br_rucker'		=> 'br_rucker',
	'de_rmay'		=> 'de_rmay',
    'de_theodor'	=> 'de_theodor',
	'de_rinalda'	=> 'de_rinalda',
    // 'en_alisha'		=> 'en_alisha',
    'in_alisha'		=> 'en_alisha',
    'uk_alisha'		=> 'en_alisha',
    'ca_alisha'		=> 'en_alisha',
    'sf_alisha'		=> 'en_alisha',
    'sg_alisha'		=> 'en_alisha',
    'nz_alisha'		=> 'en_alisha',
    'au_alisha'		=> 'en_alisha',
	'uk_aasha'		=> 'en_aasha',
	'in_aasha'		=> 'en_aasha',
	'ca_aasha'		=> 'en_aasha',
	'au_aasha'		=> 'en_aasha',
	'es_laetizia'	=> 'es_laetizia',
	'ar_laetizia'	=> 'es_laetizia',
	'cl_laetizia'	=> 'es_laetizia',
	'es_rmay'		=> 'es_rmay',
	'fr_rmay'		=> 'fr_rmay',
	'fr_laetizia'   => 'laetizia',
	'nl_laetizia'	=> 'nl_laetizia',
	'in_laetizia'	=> 'in_laetizia',
	'nl_rmay'  		=> 'nl_rmay',
	'pt_laetizia'	=> 'pt_laetizia',
	'br_laetizia'	=> 'pt_laetizia',
	'br_rmay'		=> 'pt_rmay',
	'pt_rmay'		=> 'pt_rmay',
	'fr_rinalda'	=> 'rinalda',
	'fr_rucker'		=> 'rucker',
	'it_laetizia'	=> 'it_laetizia',
	
	'dk_laetizia'	=> 'dk_laetizia',
	'se_laetizia'   => 'se_laetizia',
	'no_laetizia'   => 'no_laetizia',
	'se_rinalda'    => 'se_rinalda',
	'no_rinalda'    => 'no_rinalda',
	'dk_rinalda'    => 'dk_rinalda',
	'tr_rmay'		=> 'tr_rmay',
	'nl_rinalda'	=> 'nl_rinalda',
	'pt_rinalda'	=> 'pt_rinalda',
	'br_rinalda'	=> 'pt_rinalda',
	'de_laetizia'	=>  'de_laetizia',
	'uk_rinalda'    => 'uk_rinalda',
	'it_rinalda'		=> 'it_rinalda',
	'ca_rinalda'    => 'uk_rinalda',
	'au_rinalda'    => 'uk_rinalda',
	'dk_rmay'		=>	'dk_rmay',
	'no_ml'  		=> 'no_ml',
	// 'ie_ml'  		=> 'ie_ml',
	'it_ml'		=> 'it_ml',
	// 'gr_laetizia'	=> 'gr_laetizia',
	// 'ru_laetizia'	=> 'ru_laetizia',
	'se_rmay'		=> 'se_rmay',
	'pl_rmay'		=> 'pl_rmay',
	// 'tr_laetizia'   => 'tr_laetizia',
	'fi_laetizia'   => 'fi_laetizia',
	'fr_myriana'		=>	'fr_myriana',
	// 'fr_evamaria'		=>	'fr_evamaria',
	// 'se_althea'		=>	'se_althea',
	// 'jp_nobuko'		=>	'jp_nobuko',
	'fr_ivana'		=>	'fr_ivana',
	// 'fr_evamaria'		=>	'fr_evamaria',
	// 'fr_althea'		=>	'fr_althea',
	);
		class HBporteur
{
       

}
?>