<?php
//Porteur URL
$GLOBALS['porteurUrl'] = array(
	'fr_rinalda' => array(
		'url' => 'http://www.rin-fr.com',
		'nom' => 'Rinalda',
		'folder' => 'rinalda',
		'ratiotext' => '',
		'ratioHtml' => '1083087',
		'emvsendertxt' => '1072986',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '1072985',
		'emvSenderhtml2' => '',
		'emvImage' => '1045962',
		'emvDesFaqtxt' => '1073002',
		'emvDesFaqtxt2' => '',
		'emvDesFaqhtml' => '1072442',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.gif',
		'emvchq' => '1072984',
		'emvchqhtml' => '1072983',
		'phtml' => "\t\t\t\tPour plus d'informations ou si vous avez des questions, veuillez suivre <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>ce lien.</b></a>\n",
		'ptext' =>"\tPour plus d'informations ou si vous avez des questions, veuillez \n\tsuivre ce lien.: [EMV LINK]4[EMV /LINK] \n\n"
	),
	//verifié 

	'pt_rinalda' => array(
		'url' => 'http://www.rin-pt.com',
		'nom' => '[EMV INCLUDE]2944[EMV /INCLUDE]',
		'folder' => 'pt_rinalda',
		'ratiotext' => '3402',
		'ratioHtml' => '3401',
		'emvsendertxt' => '664',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '663',
		'emvSenderhtml2' => '',
		'emvImage' => '302',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvchq' => '306',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.gif',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tPara mais informações ou tiver dúvidas, siga <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>este link.</b></a>\n",
		'ptext' =>"\tPara mais informações ou tiver dúvidas, siga \n\teste link.: [EMV LINK]4[EMV /LINK] \n\n"
	),
	//verifié
	'br_rinalda' => array(
		'url' => 'http://www.rin-br.com',
		'nom' => 'Rinalda',
		'folder' => 'pt_rinalda',
		'ratiotext' => '3831',
		'ratioHtml' => '3830',
		'emvsendertxt' => '1736',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '1731',
		'emvSenderhtml2' => '',
		'emvImage' => '1733',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvchq' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tPara mais informações ou tiver dúvidas, siga <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>este link.</b></a>\n",
		'ptext' =>"\tPara mais informações ou tiver dúvidas, siga \n\teste link.: [EMV LINK]4[EMV /LINK] \n\n"
	),
	//verifié

	'de_rinalda' => array(
		'url' => 'http://www.rin-de.com',
		'nom' => 'Rinalda',
		'folder' => 'de_rinalda',
		'ratiotext' => '25005',
		'ratioHtml' => '20702',
		'emvsendertxt' => '20683',
		'emvsendertxt2' => '20684',
		'emvSenderhtml' => '20685',
		'emvSenderhtml2' => '',
		'emvImage' => '10886',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvDesFaqhtml' => '20702',
		'emvDesFaqhtml2' => '20682',
		'emvchq' => '',
		'imgname' => 'opt_images/signature.jpg',
		'emvchqhtml' => '',
		'emvsignature' => '',
		'phtml' => "\t\t\t\tFür mehrere Informationen oder Wenn Sie Fragen haben,Folgen Sie bitte dieses<br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>link.</b></a>\n",
		'ptext' =>"\tFür mehrere Informationen oder Wenn Sie Fragen haben, Folgen Sie bitte dieses \n\tLINK.: [EMV LINK]4[EMV /LINK] \n\n"
	),
	//verifié
	'se_rinalda' => array(
		'url' => 'http://www.rinalda-se.com',
		'nom' => 'Rinalda',
		'folder' => 'se_rinalda',
        'ratiotext' => '3372',
        'ratioHtml' => '3373',
        'emvsendertxt' => '2648',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '2646',
		'emvSenderhtml2' => '2647',
		'emvImage' => '1737',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '[EMV INCLUDE]1737[EMV /INCLUDE]images_gen/signature.jpg',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\t[EMV INCLUDE]1734[EMV /INCLUDE] <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><br /><b>[EMV INCLUDE]1739[EMV /INCLUDE]</b></a>\n",
		'ptext' =>"\t[EMV INCLUDE]1742[EMV /INCLUDE] \n\t[EMV INCLUDE]1739[EMV /INCLUDE]: [EMV LINK]4[EMV /LINK] \n\n"
	),
	//verifié
	'dk_rinalda' => array(
		'url' => 'http://www.rinalda-dk.com',
		'nom' => 'Rinalda',
		'folder' => 'dk_rinalda',
		'ratiotext' => '',		
		'ratioHtml' => '3425',
		'emvsendertxt' => '1710',
		'emvsendertxt2' => '1711',
		'emvSenderhtml' => '1713',
		'emvSenderhtml2' => '1729',
		'emvImage' => '1715',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvchq' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tHvis du vil vide mere, eller hvis du har sp&oslash;rgsm&aring;l, skal du f&oslash;lge <br /> \n \t\t\t\t <a href='[EMV LINK]3[EMV /LINK]'><b>dette link.</b></a>\n",
		'ptext' =>"\tHvis du vil vide mere, eller hvis du har spørgsmål, skal du følge \n\tLink: [EMV LINK]3[EMV /LINK] \n\n"
	),
	//verifié
	'no_rinalda' => array(
		'url' => 'http://www.rinalda-no.com',
		'nom' => 'Rinalda',
		'folder' => 'no_rinalda',
		'ratiotext' => '',		
		'ratioHtml' => '3383',
		'emvsendertxt' => '1762',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '1559',
		'emvSenderhtml2' => '',
		'emvImage' => '1560',
		'emvDesFaqhtml' => '1563',
		'emvDesFaqhtml2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvsignature' => '',
		'imgname' => 'images/images_gen/rinalda_signature.png',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\t[EMV INCLUDE]1561[EMV /INCLUDE] <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>[EMV INCLUDE]1562[EMV /INCLUDE]</b></a>\n",
		'ptext' =>"\t[EMV INCLUDE]1561[EMV /INCLUDE]  \n\t[EMV INCLUDE]1562[EMV /INCLUDE]: [EMV LINK]4[EMV /LINK]\n\n"
	),
	//verifié
	'uk_rinalda' => array(
		'url' => 'http://www.rin-uk.com',
		'nom' => 'Rinalda',
		'folder' => 'uk_rinalda',
		'ratiotext' => '',
		'ratioHtml' => '',
		'emvsendertxt' => '1110',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '1110',
		'emvSenderhtml2' => '',
		'emvImage' => '1108',
		'emvDesFaqtxt' => '1118',
		'emvDesFaqtxt2' => '',
		'emvDesFaqhtml' => '1118',
		'emvDesFaqhtml2' => '',
		'emvchq' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature_rinalda.jpg',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tFor any questions to Rinalda, please send an email to <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>Link.</b></a>\n",
		'ptext' =>"\tFor any questions to Rinalda, please send an email to  \n\tLink.: [EMV LINK]4[EMV /LINK] \n\n"
	),
	//verifié
	'it_rinalda' => array(
		'url' => 'http://www.rin-it.com',
		'nom' => '[EMV INCLUDE]2943[EMV /INCLUDE]',
		'folder' => 'it_rinalda',
		'ratiotext' => '2943',
		'ratioHtml' => '',
		'emvsendertxt' => '1310',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '1049',
		'emvSenderhtml2' => '',
		'emvImage' => '1066',
		'emvDesFaqtxt' => '1311',
		'emvDesFaqtxt2' => '',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tPer maggiori informazioni o se avete delle domande, seguite <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>questo link.</b></a>\n",
		'ptext' =>"\tPer maggiori informazioni o se avete delle domande, seguite \n\tquesto link: [EMV LINK]4[EMV /LINK] \n\n"
	),
	//verifié
	'ca_rinalda' => array(
		'url' => '',
		'nom' => 'Rinalda',
		'folder' => '',
		'ratiotext' => '',
		'ratioHtml' => '',
		'emvsendertxt' => '',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '',
		'emvSenderhtml2' => '',
		'emvImage' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqhtml' => '',
		'emvDesFaqtxt2' => '',
		'emvDesFaqhtml2' => '',
		'emvchq' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tFor any questions to Rinalda, please send an email to <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>Link.</b></a>\n",
		'ptext' =>"\tFor any questions to Rinalda, please send an email to  \n\tLink.: [EMV LINK]4[EMV /LINK] \n\n"
	),
	'au_en_rinalda' => array(
		'url' => 'http://www.rinalda-au.com',
		'nom' => 'Rinalda',
		'folder' => 'au_en_rinalda',
		'ratiotext' => '',
		'ratioHtml' => '',
		'emvsendertxt' => '',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '',
		'emvSenderhtml2' => '',
		'emvImage' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqhtml' => '',
		'emvDesFaqtxt2' => '',
		'emvDesFaqhtml2' => '',
		'emvchq' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tFor any questions to Rinalda, please send an email to <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>Link.</b></a>\n",
		'ptext' =>"\tFor any questions to Rinalda, please send an email to  \n\tLink.: [EMV LINK]4[EMV /LINK] \n\n"
	),
	'nl_rinalda' => array(
		'url' => 'http://www.rin-nl.com',
		'nom' => '[EMV INCLUDE]2941[EMV /INCLUDE]',
		'folder' => 'nl_rinalda',
		'ratiotext' => '3382',
		'ratioHtml' => '3381',
		'emvsendertxt' => '823',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '824',
		'emvSenderhtml2' => '',
		'emvImage' => '821',
		'emvDesFaqtxt' => '',
		'emvDesFaqhtml' => '',
		'emvDesFaqtxt2' => '',
		'emvDesFaqhtml2' => '',
		'emvchq' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tVoor meer informatie of als u vragen hebt, volg dan <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>die link.</b></a>\n",
		'ptext' =>"\tVoor meer informatie of als u vragen hebt, volg dan \n\tdie link.: [EMV LINK]4[EMV /LINK] \n\n"
	),
	//verifié

	'fr_laetizia' => array(
		'url' => 'http://www.laetizia-m.com',
		'nom' => 'Laetizia',
		'folder' => 'laetizia',
		'ratiotext' => '',
		'ratioHtml' => '50762',
		'emvsendertxt' => '42699',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '39479',
		'emvSenderhtml2' => '39481',
		'emvImage' => '18379',
		'emvDesFaqtxt' => '42700',
		'emvDesFaqtxt2' => '',
		'emvDesFaqhtml' => '41699',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.gif',
		'emvchq' => '42680',
		'emvchqhtml' => '42679',
		'phtml' => "\t\t\t\tPour plus d'informations ou si vous avez des questions, veuillez suivre <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>ce lien.</b></a>\n",
		'ptext' =>"\tPour plus d'informations ou si vous avez des questions, veuillez \n\tsuivre ce lien.: [EMV LINK]4[EMV /LINK] \n\n"
	),

	//verifié
	'de_laetizia' => array(
		'url' => 'http://www.laetizia-de.com',
		'nom' => 'Laetizia',
		'folder' => 'de_laetizia',
		'ratiotext' => '3406',
		'ratioHtml' => '3410',
		'emvsignature' => '',
		'imgname' => 'de_images/signature_laetizia.png',
		'emvchq' => '1366',
		'emvchqhtml' => '1365',
		'emvSenderhtml' => '665',
		'emvSenderhtml2' => '',
		'emvImage' => '670',
		'emvDesFaqhtml' => '671',
		'emvDesFaqhtml2' => '',
		'emvsendertxt' => '666',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '2847',
		'emvDesFaqtxt2' => '',
		'phtml' => "\t\t\t\tFür mehrere Informationen oder Wenn Sie Fragen haben, Folgen Sie bitte dieses <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>LINK.</b></a>\n",
		'ptext' =>"\tFür mehrere Informationen oder Wenn Sie Fragen haben, Folgen Sie bitte dieses \n\tLINK.: [EMV LINK]4[EMV /LINK] \n\n"
	),
	//verifié
	'dk_laetizia' => array(
		'url' => 'http://www.laetizia-dk.com',
		'nom' => 'Laetizia',
		'folder' => 'dk_laetizia',
		'ratiotext' => '',		
		'ratioHtml' => '3308',
		'emvsendertxt' => '513',
		'emvsendertxt2' => '2593',
		'emvsendertxt3' => '514',
		'emvSenderhtml' => '505',
		'emvSenderhtml2' => '507',
		'emvImage' =>'502',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature_laetizia.gif',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tHvis du vil vide mere, eller hvis du har sp&oslash;rgsm&aring;l, skal du f&oslash;lge <br /> \n \t\t\t\t <a href='[EMV LINK]3[EMV /LINK]'><b>dette link.</b></a>\n",
		'ptext' =>"\tHvis du vil vide mere, eller hvis du har spørgsmål, skal du følge \n\tLink: [EMV LINK]3[EMV /LINK] \n\n"
	),
	//verifié
	'es_laetizia' => array(
		'url' => 'http://www.laetizia-a.com',
		'nom' => 'Laétizia',
		'folder' => 'es_laetizia',
		'ratiotext' => '18737',
		'ratioHtml' => '18736',
		'emvsendertxt' => '16207',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '15690',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '15687',
		'emvSenderhtml2' => '',
		'emvImage' =>'3902',
		'emvDesFaqhtml' => '15688',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '15686',
		'emvchqhtml' => '15706',
		'phtml' => "\t\t\t\tPara más información o si tiene preguntas, por favor siga <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>este enlace.</b></a>\n",
		'ptext' =>"\tPara más información o si tiene preguntas, por favor siga\n\teste enlace.: [EMV LINK]4[EMV /LINK] \n\n"
	),
	//verifié	
	'cl_laetizia' => array(
		'url' => 'http://www.laetizia-ch.com',
		'nom' => 'Laétizia',
		'folder' => 'es_laetizia',
		'ratiotext' => '3583',
		'ratioHtml' => '3582',
		'emvsendertxt' => '16207',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '15690',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '15687',
		'emvSenderhtml2' => '',
		'emvImage' =>'3902',
		'emvDesFaqhtml' => '15688',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '15686',
		'emvchqhtml' => '15706',
		'phtml' => "\t\t\t\tPara más información o si tiene preguntas, por favor siga <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>este enlace.</b></a>\n",
		'ptext' =>"\tPara más información o si tiene preguntas, por favor siga\n\teste enlace.: [EMV LINK]4[EMV /LINK] \n\n"
	),	//verifié	
	'ar_laetizia' => array(
		'url' => 'http://www.laetizia-ag.com',
		'nom' => 'Laétizia',
		'folder' => 'es_laetizia',
		'ratiotext' => '3531',
		'ratioHtml' => '3530',
		'emvsendertxt' => '16207',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '15690',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '15687',
		'emvSenderhtml2' => '',
		'emvImage' =>'11746',
		'emvDesFaqhtml' => '15688',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '15686',
		'emvchqhtml' => '15706',
		'phtml' => "\t\t\t\tPara más información o si tiene preguntas, por favor siga <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>este enlace.</b></a>\n",
		'ptext' =>"\tPara más información o si tiene preguntas, por favor siga\n\teste enlace.: [EMV LINK]4[EMV /LINK] \n\n"
	),
	//verifié
	'in_laetizia' => array(
		'url' => 'http://www.laeya-m.com',
		'nom' => 'Laetizia',
		'folder' => 'in_laetizia',
		'ratiotext' => '',
		'ratioHtml' => '3377',
		'emvsendertxt' => '565',
		'emvsendertxt2' => '566',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '562',
		'emvSenderhtml2' => '568',
		'emvSenderhtml3' => '',
		'emvSenderhtml4' => '',
		'emvImage' =>'569',
		'emvDesFaqhtml' => '41699',
		'emvDesFaqhtml2' => '',
		'emvchq' => '',
		'imgname' => 'images_gen/signature_laetizia.gif',
		'emvsignature' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tFor any questions, please send an email to <br /> <a href='[EMV LINK]4[EMV /LINK]'><b>Link.</b></a>\n",
		'ptext' =>"\tFor any questions, please send an email to : [EMV LINK]4[EMV /LINK] \n\n"
	),		//verifié
	'ie_laetizia' => array(
		'url' => 'http://www.laetizia-ie.com',
		'nom' => 'Laetizia',
		'folder' => 'in_laetizia',
		'ratiotext' => '',
		'ratioHtml' => '3368',
		'emvsendertxt' => '1613',
		'emvsendertxt2' => '1614',
		'emvDesFaqtxt' => '15690',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '1615',
		'emvSenderhtml2' => '1661',
		'emvImage' =>'1616',
		'emvDesFaqhtml' => '1072442',
		'emvDesFaqhtml2' => '',
		'emvchq' => '',
		'imgname' => 'images_gen/signature_laetizia.gif',
		'emvsignature' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tFor any questions, please send an email to <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>Link.</b></a>\n",
		'ptext' =>"\tFor any questions, please send an email to\n\tLink.: [EMV LINK]4[EMV /LINK] \n\n"
	),
	//verifié
	'it_laetizia' => array(
		'url' => 'http://www.laetizia-it.com',
		'nom' => 'Laetizia',
		'folder' => 'it_laetizia',
		'ratiotext' => '2887',
		'ratioHtml' => '2886',
		'emvsendertxt' => '1152',
		'emvsendertxt2' => '1151',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		//'emvSenderhtml' => '3285',
		'emvSenderhtml' => '421',
		'emvSenderhtml2' => '',
		// 'emvImage' =>'1424',
		'emvImage' =>'422',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tPer maggiori informazioni o se avete delle domande, seguite <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>questo link.</b></a>\n",
		'ptext' =>"\tPer maggiori informazioni o se avete delle domande, seguite \n\tquesto link.: [EMV LINK]4[EMV /LINK]\n\n"
	),
	//verifié

	'nl_laetizia' => array(
		'url' => 'http://www.laetizia-nl.com',
		'nom' => '[EMV INCLUDE]2942[EMV /INCLUDE]',
		'folder' => 'nl_laetizia',
		'ratiotext' => '3387',
		'ratioHtml' => '3386',
		'emvsendertxt' => '662',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '661',
		'emvSenderhtml2' => '',
		'emvImage' =>'372',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.gif',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\tVoor meer informatie of als u vragen hebt, volg dan <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>die link.</b></a>\n",
		'ptext' =>"\tVoor meer informatie of als u vragen hebt, volg dan  \n\tdie link.: [EMV LINK]4[EMV /LINK]\n\n"
	),
	//verifié
	'no_laetizia' => array(
		'url' => 'http://www.laetizia-no.com',
		'nom' => 'Laetizia',
		'folder' => 'no_laetizia',
		'ratiotext' => '',		
		'ratioHtml' => '3292',
		'emvsendertxt' => '1418',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '1415',
		'emvSenderhtml2' => '',
		'emvImage' =>'520',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature_laetizia.gif',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\t[EMV INCLUDE]515[EMV /INCLUDE]  <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'> <b>[EMV INCLUDE]516[EMV /INCLUDE]</b></a>\n",
		'ptext' =>"\t[EMV INCLUDE]515[EMV /INCLUDE] \n\t Linken.:  [EMV LINK]4[EMV /LINK]\n\n"
	),
	//verifié
	'pt_laetizia' => array(
		'url' => 'http://www.laetizia-v.com',
		'nom' => 'Laetizia',
		'folder' => 'pt_laetizia',
		'ratiotext' => '',
		'ratioHtml' => '18735',
		'emvsendertxt' => '15727',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '15726',
		'emvSenderhtml2' => '',
		'emvImage' =>'11526',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvDesFaqhtml' => '000000',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '15730',
		'emvchqhtml' => '15731',
		'phtml' => "\t\t\t\t[EMV INCLUDE]16147[EMV /INCLUDE] <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'> <b>[EMV INCLUDE]16148[EMV /INCLUDE]</b></a>\n",
		'ptext' =>"\tPara mais informaç?es ou tiver d?vidas, siga  \n\teste link: [EMV LINK]4[EMV /LINK]\n\n"
	),

	//vierifié

	'br_laetizia' => array(
		'url' => ' http://www.laetizia-br.com',
		'nom' => 'Laetizia',
		'folder' => 'pt_laetizia',
		'ratiotext' => '',
		'ratioHtml' => '3291',
		'emvsendertxt' => '3043',
		'emvsendertxt2' => '3042',
		'emvSenderhtml' => '1608',
		'emvSenderhtml2' => '1609',
		'emvImage' =>'1558',
		'emvDesFaqtxt' => '3293',
		'emvDesFaqtxt2' => '3043',
		'emvDesFaqtxt3' => '3042',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\t[EMV INCLUDE]1605[EMV /INCLUDE] <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'> <b>[EMV INCLUDE]1606[EMV /INCLUDE]</b></a>\n",
		'ptext' =>"\tPara mais informaç?es ou tiver d?vidas, siga  \n\teste link: [EMV LINK]4[EMV /LINK]\n\n"
	),

	//*****util
	'se_laetizia' => array(
		'url' => 'http://www.laetizia-se.com',
		'nom' => 'Laetizia',
		'folder' => 'se_laetizia',
        'ratiotext' => '3314',		
        'ratioHtml' => '3315',
		'emvsendertxt' => '1452',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvsignature' => '',
		'emvSenderhtml' => '536',
		'emvSenderhtml2' => '',
		'emvImage' =>'537',
		'emvDesFaqhtml' => '538',
		'emvDesFaqhtml2' => '',
		'emvchq' => '',
		'imgname' => 'images_gen/signature_laetizia.gif',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tHvis du vil vide mere, eller hvis du har spørgsmål, skal du følge <br /> \n \t\t\t\t  <a href='[EMV LINK]4[EMV /LINK]'><b>dette link.</b></a> \n",
		'ptext' =>"\tHvis du vil vide mere, eller hvis du har spørgsmål, skal du følge \n\tLink: [EMV LINK]4[EMV /LINK]\n\n"
	),

	//verifié
	'fr_rmay' => array(
		'url' => 'http://www.r-may.com',
		'nom' => 'Mona Louisa',
		'folder' => 'fr_rmay',
		'ratioText' => '19250',
		'ratioHtml' => '19249',
		'emvsendertxt' => '11769',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '14972',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '11569',
		'emvSenderhtml2' => '',
		'emvImage' =>'1203',
		'emvDesFaqhtml' => '14971',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '10910',
		'emvchqhtml' => '10909',
		'phtml' => "\t\t\t\tPour plus d'informations ou si vous avez des questions, veuillez suivre <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>ce lien.</b></a>\n",
		'ptext' =>"\tPour plus d'informations ou si vous avez des questions, veuillez suivre \n\tce lien.: [EMV LINK]4[EMV /LINK]\n\n"
	),
	'dk_rmay' => array(
		'url' => 'http://www.r-maydk.com',
		'nom' => 'Mona Luisa',
		'folder' => 'dk_rmay',
		'ratiotext' => '',
		'ratioHtml' => '',
		'emvsendertxt' => '2710',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '2708',
		'emvSenderhtml2' => '',
		'emvImage' =>'2264',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tPara mais informações ou tiver dúvidas, siga <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>dette link.</b></a>\n",
		'ptext' =>"\tHvis du vil vide mere, eller hvis du har spørgsmål, skal du følge \n\tLink: [EMV LINK]3[EMV /LINK] \n\n"
	),
	'no_ml' => array(
		'url' => 'http://www.r-mayno.com',
		'nom' => '[EMV INCLUDE]2945[EMV /INCLUDE]',
		'folder' => 'no_ml',
		'ratiotext' => '4226',
		'ratioHtml' => '4227',
		'emvsendertxt' => '',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '',
		'emvSenderhtml2' => '',
		'emvImage' =>'',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\t \n \t\t\t\t \n",
		'ptext' =>"\t    \n\t  \n\n"
	),
	'ie_ml' => array(
		'url' => 'http://www.r-mayno.com',
		'nom' => 'Mona Luisa',
		'folder' => 'ie_ml',
		'ratiotext' => '',
		'ratioHtml' => '',
		'emvsendertxt' => '',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '',
		'emvSenderhtml2' => '',
		'emvImage' =>'',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tFor any questions, please send an email to <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>Link.</b></a>\n",
		'ptext' =>"\tFor any questions, please send an email to\n\tLink.: [EMV LINK]4[EMV /LINK] \n\n"
	),
	'it_ml' => array(
		'url' => 'http://www.r-mayit.com',
		'nom' => 'Mona Luisa',
		'folder' => 'it_ml',
		'ratiotext' => '',
		'ratioHtml' => '',
		'emvsendertxt' => '2764',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '2750',
		'emvSenderhtml2' => '',
		'emvImage' =>'2751',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tPer maggiori informazioni o se avete delle domande, seguite <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>questo link.</b></a>\n",
		'ptext' =>"\tPer maggiori informazioni o se avete delle domande, seguite \n\tquesto link.: [EMV LINK]4[EMV /LINK]\n\n"
	),
	//verifié
	'de_rmay' => array(
		'url' => 'http://www.rmayd.com',
		'nom' => 'Mona Luisa',
		'folder' => 'de_rmay',
		'ratiotext' => '12542',
		'ratioHtml' => '12375',
		'emvsendertxt' => '10783',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '10782',
		'emvSenderhtml2' => '',
		'emvDesFaqtxt' => '12542',
		'emvDesFaqtxt2' => '10783',
		'emvImage' =>'83',
		'emvDesFaqhtml' => '12375',
		'emvDesFaqhtml2' => '10782',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.png',
		'emvchq' => '2601',
		'emvchqhtml' => '2602',
		'phtml' => "\t\t\t\tFür mehrere Informationen oder Wenn Sie Fragen haben,Folgen Sie bitte dieses <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>LINK.</b></a>\n",
		'ptext' =>"\tFür mehrere Informationen oder Wenn Sie Fragen haben, \n\tFolgen Sie bitte dieses LINK.: [EMV LINK]4[EMV /LINK]\n\n"
	),
	//verifié
	'es_rmay' => array(
		'url' => 'http://www.mluisa-e.com',
		'nom' => 'Mona Luisa',
		'folder' => 'es_rmay',
		'ratiotext' => '21121',
		'ratioHtml' => '21120',
		'emvsendertxt' => '19141',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '18420',
		'emvSenderhtml2' => '',
		'emvImage' =>'4221',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '19100',
		'emvchqhtml' => '19120',
		'phtml' => "\t\t\t\tPara m&aacute;s informaci&oacute;n o si tiene preguntas, por favor siga<br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>este enlace.</b></a>\n",
		'ptext' =>"\tPara más información o si tiene preguntas, por favor siga \n\teste enlace.: [EMV LINK]4[EMV /LINK]\n\n"
	),
	'gr_laetizia' => array(
		'url' => 'http://www.laetizia-gr.com',
		'nom' => 'Mona Luisa',
		'folder' => 'gr_laetizia',
		'ratiotext' => '',
		'ratioHtml' => '',
		'emvsendertxt' => '',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '',
		'emvSenderhtml2' => '',
		'emvImage' =>'',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => '',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tPara m&aacute;s informaci&oacute;n o si tiene preguntas, por favor siga<br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>este enlace.</b></a>\n",
		'ptext' =>"\tPara más información o si tiene preguntas, por favor siga \n\teste enlace.: [EMV LINK]4[EMV /LINK]\n\n"
	),
	'ru_laetizia' => array(
		'url' => '',
		'nom' => 'Mona Luisa',
		'folder' => 'ru_laetizia',
		'ratiotext' => '',
		'ratioHtml' => '',
		'emvsendertxt' => '',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '',
		'emvSenderhtml2' => '',
		'emvImage' =>'',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => '',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tPara m&aacute;s informaci&oacute;n o si tiene preguntas, por favor siga<br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>este enlace.</b></a>\n",
		'ptext' =>"\tPara más información o si tiene preguntas, por favor siga \n\teste enlace.: [EMV LINK]4[EMV /LINK]\n\n"
	),
	'se_rmay' => array(
		'url' => 'http://www.r-mayse.com',
		'nom' => 'Mona Luisa',
		'folder' => 'se_rmay',
		'ratiotext' => '',
		'ratioHtml' => '',
		'emvsendertxt' => '3114',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '3113',
		'emvSenderhtml2' => '',
		'emvImage' =>'3109',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tHvis du vil vide mere, eller hvis du har spørgsmål, skal du følge <br /> \n \t\t\t\t  <a href='[EMV LINK]4[EMV /LINK]'><b>dette link.</b></a> \n",
		'ptext' =>"\tHvis du vil vide mere, eller hvis du har spørgsmål, skal du følge \n\tLink: [EMV LINK]4[EMV /LINK]\n\n"
	),
	'fi_laetizia' => array(
		'url' => '',
		'nom' => 'Laetizia',
		'folder' => 'fi_laetizia',
		'ratiotext' => '',
		'ratioHtml' => '',
		'emvsendertxt' => '',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '',
		'emvSenderhtml2' => '',
		'emvImage' =>'',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => '',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tPara m&aacute;s informaci&oacute;n o si tiene preguntas, por favor siga<br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>este enlace.</b></a>\n",
		'ptext' =>"\tPara más información o si tiene preguntas, por favor siga \n\teste enlace.: [EMV LINK]4[EMV /LINK]\n\n"
	),
	//verifié

	'nl_rmay' => array(
		'url' => 'http://www.mluisa-n.com',
		'nom' => 'Mona Luisa',
		'folder' => 'nl_rmay',
		'ratiotext' => '7182',
		'ratioHtml' => '7181',
		'emvsendertxt' => '3285',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '1425',
		'emvSenderhtml2' => '',
		'emvImage' =>'1424',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '2601',
		'emvchqhtml' => '2602',
		'phtml' => "\t\t\t\tVoor meer informatie of als u vragen hebt, volg dan <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>deze link.</b></a>\n",
		'ptext' =>"\tVoor meer informatie of als u vragen hebt, volg dan deze link : \n\t[EMV LINK]4[EMV /LINK]\n\n"
	),
	'cl_rmay' => array(
		'url' => 'http://www.mluisa-n.com',
		'nom' => 'Mona Luisa',
		'folder' => 'cl_rmay',
		'ratiotext' => '',
		'ratioHtml' => '',
		'emvsendertxt' => '',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '',
		'emvSenderhtml2' => '',
		'emvImage' =>'',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '2601',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tVoor meer informatie of als u vragen hebt, volg dan <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>deze link.</b></a>\n",
		'ptext' =>"\tVoor meer informatie of als u vragen hebt, volg dan deze link : \n\t[EMV LINK]4[EMV /LINK]\n\n"
	),
	//verifié

	'br_rmay' => array(
		'url' => 'http://www.r-may-br.com',
		'nom' => 'Mona Luisa',
		'folder' => 'pt_rmay',
		'ratiotext' => '',		
		'ratioHtml' => '3380',
		'emvsendertxt' => '1551',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '1553',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '1554',
		'emvSenderhtml2' => '',
		'emvImage' =>'3271',
		'emvDesFaqhtml' => '3380',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '10909',
		'emvchqhtml' => '10910',
		'phtml' => "\t\t\t\t[EMV INCLUDE]1556[EMV /INCLUDE] <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>este link</b></a>\n",
		'ptext' =>"\t[EMV INCLUDE]1556[EMV /INCLUDE] \n\t: [EMV LINK]4[EMV /LINK]\n\n"
	),
	'pt_rmay' => array(
		'url' => 'http://www.mluisa-b.com',
		'nom' => 'Mona Luisa',
		'folder' => 'pt_rmay',
		'ratiotext' => '',		
		'ratioHtml' => '24468',
		'emvsendertxt' => '22367',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '20164',
		'emvSenderhtml2' => '',
		'emvImage' =>'10545',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '10909',
		'emvchqhtml' => '10910',
		'phtml' => "\t\t\t\t[EMV INCLUDE]22605[EMV /INCLUDE] <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>[EMV INCLUDE]20167[EMV /INCLUDE]</b></a>\n",
		'ptext' =>"\t[EMV INCLUDE]22604[EMV /INCLUDE] \n\t: [EMV LINK]4[EMV /LINK]\n\n"
	),
	'tr_rmay' => array(
		'url' => 'http://www.r-maytr.com',
		'nom' => 'Mona Luisa',
		'folder' => 'tr_rmay',
		'ratiotext' => '',
		'ratioHtml' => '3287',
		'emvsendertxt' => '368',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '367',
		'emvSenderhtml2' => '',
		'emvImage' =>'366',
		'emvDesFaqhtml' => '370',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\t[EMV INCLUDE]371[EMV /INCLUDE]<br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>[EMV INCLUDE]621[EMV /INCLUDE]  [EMV INCLUDE]675[EMV /INCLUDE]</b></a>\n",
		'ptext' =>"\t[EMV INCLUDE]621[EMV /INCLUDE] \n\t[EMV INCLUDE]675[EMV /INCLUDE]: [EMV LINK]4[EMV /LINK]\n\n"
	),
	'pl_rmay' => array(
		'url' => 'http://www.r-maypl.com',
		'nom' => 'Mona Luisa',
		'folder' => 'pl_rmay',
		'emvsendertxt' => '4224',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '4223',
		'emvSenderhtml2' => '',
		'emvImage' =>'2356',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tAby uzyskać więcej informacji lub masz pytania, proszę na<br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>ten link.</b></a>\n",
		'ptext' =>"\tAby uzyskać więcej informacji lub masz pytania, proszę na ten link.:\n\t[EMV LINK]4[EMV /LINK]\n\n"
	),	

	//verified
	'de_theodor' => array(
		'url' => 'http://www.de-theo.com',
		'nom' => 'Theodor',
		'folder' => 'de_theodor',
		'ratiotext' => '25011',
		'ratioHtml' => '25010',
		'emvsendertxt' => '21503',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '24554',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '21502',
		'emvSenderhtml2' => '',
		'emvImage' =>'4470',
		'emvDesFaqhtml' => '24553',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '4475',
		'emvchqhtml' => '4477',
		'phtml' => "\t\t\t\tFür mehrere Informationen oder Wenn Sie Fragen haben,Folgen Sie bitte dieses<br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>LINK.</b></a>\n",
		'ptext' =>"\tFür mehrere Informationen oder Wenn Sie Fragen haben, \n\tFolgen Sie bitte dieses LINK.:[EMV LINK]4[EMV /LINK]\n\n"
	),



	// 'br_rucker' => array(
	// 	'url' => 'http://www.theo-r.com',
	// 	'nom' => 'br_rucker',
	// 	'folder' => 'de_theodor',
	// 	'emvsendertxt' => '20407',
	// 	'emvsendertxt2' => '',
	// 	'emvDesFaqtxt' => '20406',
	// 	'emvDesFaqtxt2' => '',
	// 	'emvSenderhtml' => '20402',
	// 	'emvSenderhtml2' => '',
	// 	'emvImage' =>'4470',
	// 	'emvDesFaqhtml' => '20405',
	// 	'emvDesFaqhtml2' => '',
	// 	'emvsignature' => '',
	// 	'imgname' => 'images_gen/signature.jpg',
	// 	'emvchq' => '4475',
	// 	'emvchqhtml' => '4477',
	// 	'phtml' => "\t\t\t\tFür mehrere Informationen oder Wenn Sie Fragen haben<br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>[EMV INCLUDE]621[EMV /INCLUDE]  [EMV INCLUDE]675[EMV /INCLUDE]</b></a>\n",
	// 	'ptext' =>"\tFür mehrere Informationen oder Wenn Sie Fragen haben, \n\tFolgen Sie bitte dieses LINK.:[EMV LINK]4[EMV /LINK]\n\n"
	// ),


	//theodor fid_fr
	'fr_rucker' => array(
		'url' => 'http://www.ac-ruck.com',
		'nom' => 'Théodor',
		'folder' => 'rucker',
		'ratiotext' => '25012',
		'ratioHtml' => '25013',
		'emvsendertxt' => '9711',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '9708',
		'emvSenderhtml2' => '',
		'emvImage' =>'2823',
		'emvDesFaqhtml' => '9709',
		'emvDesFaqhtml2' => '9712',
		'emvDesFaqtxt' => '9710',
		'emvDesFaqtxt2' => '5790',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '5323',
		'emvchqhtml' => '5322',
		'phtml' => "\t\t\t\tPour plus d'informations ou si vous avez des questions, veuillez suivre <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>ce lien.</b></a>\n",
		'ptext' =>"\tPour plus d'informations ou si vous avez des questions, veuillez \n\tsuivre ce lien.: [EMV LINK]4[EMV /LINK]\n\n"
	),
	'fr_rucker_acq' => array(
		'url' => 'http://www.ruckf.com',
		'nom' => 'Théodor',
		'folder' => 'rucker',
		'ratiotext' => '62447',
		'ratioHtml' => '62448',
		'emvsendertxt' => '55766',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '55763',
		'emvSenderhtml2' => '',
		'emvImage' =>'34622',
		'emvDesFaqhtml' => '55764',
		'emvDesFaqhtml2' => '53530',
		'emvDesFaqtxt' => '55765',
		'emvDesFaqtxt2' => '53532',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.gif',
		'emvchq' => '52882',
		'emvchqhtml' => '52874',
		'phtml' => "\t\t\t\tPour plus d'informations ou si vous avez des questions, veuillez suivre <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>ce lien.</b></a>\n",
		'ptext' =>"\tPour plus d'informations ou si vous avez des questions, veuillez \n\tsuivre ce lien.: [EMV LINK]4[EMV /LINK]\n\n"
	),


	//verified


	'en_alisha' => array(
		'url' => 'http://www.ali-in.com',
		'nom' => 'Alisha',
		'folder' => 'en_alisha',
		'ratiotext' => '',
		'ratioHtml' => '',
		'emvsendertxt' => '8321',
		'emvsendertxt2' => '',
		'emvsendertxt3' => '7762',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '8048',
		'emvSenderhtml2' => '7761',
		'emvImage' =>'489',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/img_signature.gif',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tFor any questions, please send an email to <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>Link.</b></a>\n",
		'ptext' =>"\tFor any questions, please send an email to \n\tLink.: [EMV LINK]4[EMV /LINK]\n\n"
	),
	//verified
	//Aasha dfid us
	'en_aasha' => array(
		'url' => 'http://www.aasha-f.com',
		'nom' => 'Aasha',
		'folder' => 'en_aasha',
		'ratiotext' => '',
		'ratioHtml' => '1000009828',
		'emvsendertxt' => '1000008448',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '1000008368',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '1000008447',
		'emvSenderhtml2' => '',
		'emvImage' =>'1000005109',
		'emvDesFaqhtml' => '1000008347',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature_aasha.gif',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tFor any questions to Aasha, please send an email to <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>Link.</b></a>\n",
		'ptext' =>"\tFor any questions to Aasha, please send an email to \n\tLink: [EMV LINK]4[EMV /LINK]\n\n"
	),
	'en_aasha_acq' => array(
		'url' => 'http://www.aasha-online.com',
		'nom' => 'Aasha',
		'folder' => 'en_aasha',
		'ratiotext' => '',
		'ratioHtml' => '62445',
		'emvsendertxt' => '58542',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '58364',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '58541',
		'emvSenderhtml2' => '',
		'emvImage' =>'44104',
		'emvDesFaqhtml' => '58363',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature_aasha.gif',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tFor any questions to Aasha, please send an email to <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>Link.</b></a>\n",
		'ptext' =>"\tFor any questions to Aasha, please send an email to \n\tLink: [EMV LINK]4[EMV /LINK]\n\n"
	),
	'tr_laetizia' => array(
		'url' => 'http://www.laet-tr.com',
		'nom' => 'Laetizia',
		'folder' => 'tr_laetizia',
		'ratioHtml' => '1111',
		'ratiotext' => '2222',
		'emvsendertxt' => '373700',	
	'emvsendertxt2' => '',
		'emvDesFaqtxt' => '3741000',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '4646',
		'emvSenderhtml2' => '3739',
		'emvImage' =>'3740',
		'emvDesFaqhtml' => '3742',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature_Laetizia.gif',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\t[EMV INCLUDE]4653[EMV /INCLUDE]<br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>[EMV INCLUDE]4654[EMV /INCLUDE]  [EMV INCLUDE]4655[EMV /INCLUDE]</b></a>\n",
		'ptext' =>"\t[EMV INCLUDE]4654[EMV /INCLUDE] \n\t[EMV INCLUDE]4655[EMV /INCLUDE]: [EMV LINK]4[EMV /LINK]\n\n"
	)
);



