<?php
//Porteur URL
$GLOBALS['porteurUrl'] = array(
'fr_althea' => array(
		'url' => 'http://www.althea-fr.com',
		'nom' => 'Althea',
		'folder' => 'fr_althea',
		'ratioText' => '7052',
		'ratioHtml' => '7051',
		'emvsendertxt' => '7041',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '7043',
		'emvSenderhtml2' => '',
		'emvImage' => '7044',
		'emvDesFaqtxt' => '7042',
		'emvDesFaqtxt2' => '',
		'emvDesFaqhtml' => '7047',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.gif',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tPour plus d'informations ou si vous avez des questions, veuillez suivre <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>ce lien.</b></a>\n",
		'ptext' =>"\tPour plus d'informations ou si vous avez des questions, veuillez \n\tsuivre ce lien.: [EMV LINK]4[EMV /LINK] \n\n"
	),	
		'fr_davina' => array(
		'url' => 'http://www.davina-fr.com',
		'nom' => 'Davina',
		'folder' => 'fr_davina',
		'ratioText' => '8675',
		'ratioHtml' => '10008',
		'emvsendertxt' => '8635',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '8636',
		'emvSenderhtml2' => '',
		'emvImage' => '8676',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.gif',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tPour plus d'informations ou si vous avez des questions, veuillez suivre <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>ce lien.</b></a>\n",
		'ptext' =>"\tPour plus d'informations ou si vous avez des questions, veuillez \n\tsuivre ce lien.: [EMV LINK]4[EMV /LINK] \n\n"
	),
		
	'fr_myriana' => array(
		'url' => 'http://www.myriana-fr.com',
		'nom' => 'Myriana',
		'folder' => 'fr_myriana',
		'ratioText' => '5154',
		'ratioHtml' => '5159',
		'emvsendertxt' => '5151',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '5157',
		'emvSenderhtml2' => '',
		'emvImage' => '5149',
		'emvDesFaqtxt' => '5152',
		'emvDesFaqtxt2' => '5153',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.gif',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tPour plus d'informations ou si vous avez des questions, veuillez suivre <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>ce lien.</b></a>\n",
		'ptext' =>"\tPour plus d'informations ou si vous avez des questions, veuillez \n\tsuivre ce lien.: [EMV LINK]4[EMV /LINK] \n\n"
	),	
	'fr_evamaria' => array(
		'url' => 'http://www.evamaria-fr.com',
		'nom' => 'Eva Maria',
		'folder' => 'fr_evamaria',
		'ratioText' => '5224',
		'ratioHtml' => '5223',
		'emvsendertxt' => '5147',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '5184',
		'emvSenderhtml2' => '',
		'emvImage' => '5150',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.gif',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tPour plus d'informations ou si vous avez des questions, veuillez suivre <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>ce lien.</b></a>\n",
		'ptext' =>"\tPour plus d'informations ou si vous avez des questions, veuillez \n\tsuivre ce lien.: [EMV LINK]4[EMV /LINK] \n\n"
	),
	'fr_rinalda' => array(
		'url' => 'http://www.rin-fr.com',
		'nom' => 'Rinalda',
		'folder' => 'rinalda',
		'ratioText' => '',
		'ratioHtml' => '1083087',
		'emvsendertxt' => '1072986',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '1072985',
		'emvSenderhtml2' => '',
		'emvImage' => '1045962',
		'emvDesFaqtxt' => '1073002',
		'emvDesFaqtxt2' => '',
		'emvDesFaqhtml' => '1072442',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.gif',
		'emvchq' => '1072984',
		'emvchqhtml' => '1072983',
		'phtml' => "\t\t\t\tPour plus d'informations ou si vous avez des questions, veuillez suivre <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>ce lien.</b></a>\n",
		'ptext' =>"\tPour plus d'informations ou si vous avez des questions, veuillez \n\tsuivre ce lien.: [EMV LINK]4[EMV /LINK] \n\n"
	),
	//verifié 

	'pt_rinalda' => array(
		'url' => 'http://www.rin-pt.com',
		'nom' => '[EMV INCLUDE]2944[EMV /INCLUDE]',
		'folder' => 'pt_rinalda',
		'ratioText' => '3402',
		'ratioHtml' => '3401',
		'emvsendertxt' => '664',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '663',
		'emvSenderhtml2' => '',
		'emvImage' => '302',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvchq' => '306',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.gif',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tPara mais informações ou tiver dúvidas, siga <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>este link.</b></a>\n",
		'ptext' =>"\tPara mais informações ou tiver dúvidas, siga \n\teste link.: [EMV LINK]4[EMV /LINK] \n\n"
	),
	//verifié
	'br_rinalda' => array(
		'url' => 'http://www.rin-br.com',
		'nom' => 'Rinalda',
		'folder' => 'pt_rinalda',
		'ratioText' => '3831',
		'ratioHtml' => '3830',
		'emvsendertxt' => '1736',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '1731',
		'emvSenderhtml2' => '',
		'emvImage' => '1733',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvchq' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tPara mais informações ou tiver dúvidas, siga <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>este link.</b></a>\n",
		'ptext' =>"\tPara mais informações ou tiver dúvidas, siga \n\teste link.: [EMV LINK]4[EMV /LINK] \n\n"
	),
	//verifié

	'de_rinalda' => array(
		'url' => 'http://www.rin-de.com',
		'nom' => 'Rinalda',
		'folder' => 'de_rinalda',
		'ratioText' => '25005',
		'ratioHtml' => '25006',
		'emvsendertxt' => '20683',
		'emvsendertxt2' => '20684',
		'emvSenderhtml' => '20685',
		'emvSenderhtml2' => '',
		'emvImage' => '10886',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvDesFaqhtml' => '20702',
		'emvDesFaqhtml2' => '20682',
		'emvchq' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchqhtml' => '',
		'emvsignature' => '',
		'phtml' => "\t\t\t\tFür mehrere Informationen oder Wenn Sie Fragen haben,Folgen Sie bitte dieses<br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>link.</b></a>\n",
		'ptext' =>"\tFür mehrere Informationen oder Wenn Sie Fragen haben, Folgen Sie bitte dieses \n\tLINK.: [EMV LINK]4[EMV /LINK] \n\n"
	),
	//verifié
	'se_rinalda' => array(
		'url' => 'http://www.rinalda-se.com',
		'nom' => 'Rinalda',
		'folder' => 'se_rinalda',
        'ratioText' => '3372',
        'ratioHtml' => '3373',
        'emvsendertxt' => '2648',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '2646',
		'emvSenderhtml2' => '2647',
		'emvImage' => '1737',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '[EMV INCLUDE]1737[EMV /INCLUDE]images_gen/signature.jpg',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\t[EMV INCLUDE]1734[EMV /INCLUDE] <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><br /><b>[EMV INCLUDE]1739[EMV /INCLUDE]</b></a>\n",
		'ptext' =>"\t[EMV INCLUDE]1742[EMV /INCLUDE] \n\t[EMV INCLUDE]1739[EMV /INCLUDE]: [EMV LINK]4[EMV /LINK] \n\n"
	),
	//verifié
	'dk_rinalda' => array(
		'url' => 'http://www.rinalda-dk.com',
		'nom' => 'Rinalda',
		'folder' => 'dk_rinalda',
		'ratioText' => '',		
		'ratioHtml' => '3425',
		'emvsendertxt' => '7699',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '7695',
		'emvSenderhtml2' => '',
		'emvImage' => '1715',
		'emvDesFaqhtml' => '7697',
		'emvDesFaqhtml2' => '',
		'emvDesFaqtxt' => '7700',
		'emvDesFaqtxt2' => '',
		'emvchq' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tHvis du vil vide mere, eller hvis du har sp&oslash;rgsm&aring;l, skal du f&oslash;lge <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>dette link.</b></a>\n",
		'ptext' =>"\tHvis du vil vide mere, eller hvis du har spørgsmål, skal du følge \n\tLink: [EMV LINK]4[EMV /LINK] \n\n"
	),
	//verifié
	'no_rinalda' => array(
		'url' => 'http://www.rinalda-no.com',
		'nom' => 'Rinalda',
		'folder' => 'no_rinalda',
		'ratioText' => '',		
		'ratioHtml' => '3383',
		'emvsendertxt' => '1762',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '1559',
		'emvSenderhtml2' => '',
		'emvImage' => '1560',
		'emvDesFaqhtml' => '1563',
		'emvDesFaqhtml2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvsignature' => '',
		'imgname' => 'images/images_gen/rinalda_signature.png',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\t[EMV INCLUDE]1561[EMV /INCLUDE] <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>[EMV INCLUDE]1562[EMV /INCLUDE]</b></a>\n",
		'ptext' =>"\t[EMV INCLUDE]1561[EMV /INCLUDE]  \n\t[EMV INCLUDE]1562[EMV /INCLUDE]: [EMV LINK]4[EMV /LINK]\n\n"
	),
	//verifié
	'uk_rinalda' => array(
		'url' => 'http://www.rin-uk.com',
		'nom' => 'Rinalda',
		'folder' => 'uk_rinalda',
		'ratioText' => '',
		'ratioHtml' => '',
		'emvsendertxt' => '1110',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '1110',
		'emvSenderhtml2' => '',
		'emvImage' => '1108',
		'emvDesFaqtxt' => '1118',
		'emvDesFaqtxt2' => '',
		'emvDesFaqhtml' => '1118',
		'emvDesFaqhtml2' => '',
		'emvchq' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature_rinalda.jpg',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tFor any questions to Rinalda, please send an email to <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>Link.</b></a>\n",
		'ptext' =>"\tFor any questions to Rinalda, please send an email to  \n\tLink.: [EMV LINK]4[EMV /LINK] \n\n"
	),
	//verifié
	'it_rinalda' => array(
		'url' => 'http://www.rin-it.com',
		'nom' => '[EMV INCLUDE]2943[EMV /INCLUDE]',
		'folder' => 'it_rinalda',
		'ratioText' => '3375',
		'ratioHtml' => '3374',
		'emvsendertxt' => '1310',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '1049',
		'emvSenderhtml2' => '',
		'emvImage' => '1066',
		'emvDesFaqtxt' => '1311',
		'emvDesFaqtxt2' => '',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tPer maggiori informazioni o se avete delle domande, seguite <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>questo link.</b></a>\n",
		'ptext' =>"\tPer maggiori informazioni o se avete delle domande, seguite \n\tquesto link: [EMV LINK]4[EMV /LINK] \n\n"
	),
	//verifié
	'ca_rinalda' => array(
		'url' => 'http://www.rinalda-ca.com',
		'nom' => 'Rinalda',
		'folder' => 'ca_rinalda',
		'ratioText' => '4441',
		'ratioHtml' => '4432',
		'emvsendertxt' => '2204',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '2179',
		'emvSenderhtml2' => '',
		'emvImage' => '2203',
		'emvDesFaqtxt' => '',
		'emvDesFaqhtml' => '',
		'emvDesFaqtxt2' => '',
		'emvDesFaqhtml2' => '',
		'emvchq' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.gif',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tFor any questions to Rinalda, please send an email to <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>Link.</b></a>\n",
		'ptext' =>"\tFor any questions to Rinalda, please send an email to  \n\tLink.: [EMV LINK]4[EMV /LINK] \n\n"
	),
	'au_en_rinalda' => array(
		'url' => 'http://www.rinalda-au.com',
		'nom' => 'Rinalda',
		'folder' => 'au_en_rinalda',
		'ratioText' => '4446',
		'ratioHtml' => '4445',
		'emvsendertxt' => '1978',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '1979',
		'emvSenderhtml2' => '',
		'emvImage' => '1976',
		'emvDesFaqtxt' => '',
		'emvDesFaqhtml' => '',
		'emvDesFaqtxt2' => '',
		'emvDesFaqhtml2' => '',
		'emvchq' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.gif',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tFor any questions to Rinalda, please send an email to <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>Link.</b></a>\n",
		'ptext' =>"\tFor any questions to Rinalda, please send an email to  \n\tLink.: [EMV LINK]4[EMV /LINK] \n\n"
	),
	'nl_rinalda' => array(
		'url' => 'http://www.rin-nl.com',
		'nom' => '[EMV INCLUDE]2941[EMV /INCLUDE]',
		'folder' => 'nl_rinalda',
		'ratioText' => '3382',
		'ratioHtml' => '3381',
		'emvsendertxt' => '823',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '824',
		'emvSenderhtml2' => '',
		'emvImage' => '821',
		'emvDesFaqtxt' => '',
		'emvDesFaqhtml' => '',
		'emvDesFaqtxt2' => '',
		'emvDesFaqhtml2' => '',
		'emvchq' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tVoor meer informatie of als u vragen hebt, volg dan <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>die link.</b></a>\n",
		'ptext' =>"\tVoor meer informatie of als u vragen hebt, volg dan \n\tdie link.: [EMV LINK]4[EMV /LINK] \n\n"
	),
	//verifié

	'fr_laetizia' => array(
		'url' => 'http://www.laetizia-m.com',
		'nom' => 'Laetizia',
		'folder' => 'laetizia',
		'ratioText' => '',
		'ratioHtml' => '50762',
		'emvsendertxt' => '42699',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '39479',
		'emvSenderhtml2' => '39481',
		'emvImage' => '18379',
		'emvDesFaqtxt' => '42700',
		'emvDesFaqtxt2' => '',
		'emvDesFaqhtml' => '41699',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.gif',
		'emvchq' => '42680',
		'emvchqhtml' => '42679',
		'phtml' => "\t\t\t\tPour plus d'informations ou si vous avez des questions, veuillez suivre <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>ce lien.</b></a>\n",
		'ptext' =>"\tPour plus d'informations ou si vous avez des questions, veuillez \n\tsuivre ce lien.: [EMV LINK]4[EMV /LINK] \n\n"
	),

	//verifié
	'de_laetizia' => array(
		'url' => 'http://www.laetizia-de.com',
		'nom' => 'Laetizia',
		'folder' => 'de_laetizia',
		'ratioText' => '3406',
		'ratioHtml' => '3410',
		'emvsignature' => '',
		'imgname' => 'de_images/signature_laetizia.png',
		'emvchq' => '1366',
		'emvchqhtml' => '1365',
		'emvSenderhtml' => '7289',
		'emvSenderhtml2' => '',
		'emvImage' => '670',
		'emvDesFaqhtml' => '7308',
		'emvDesFaqhtml2' => '',
		'emvsendertxt' => '7322',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '7319',
		'emvDesFaqtxt2' => '',
		'phtml' => "\t\t\t\tFür mehrere Informationen oder Wenn Sie Fragen haben, Folgen Sie bitte dieses <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>LINK.</b></a>\n",
		'ptext' =>"\tFür mehrere Informationen oder Wenn Sie Fragen haben, Folgen Sie bitte dieses \n\tLINK.: [EMV LINK]4[EMV /LINK] \n\n"
	),
	//verifié
	'dk_laetizia' => array(
		'url' => 'http://www.laetizia-dk.com',
		'nom' => 'Laetizia',
		'folder' => 'dk_laetizia',
		'ratioText' => '',		
		'ratioHtml' => '3308',
		'emvsendertxt' => '7742',
		'emvsendertxt2' => '',
		'emvsendertxt3' => '',
		'emvSenderhtml' => '7738',
		'emvSenderhtml2' => '',
		'emvImage' =>'502',
		'emvDesFaqtxt' => '7746',
		'emvDesFaqtxt2' => '',
		'emvDesFaqhtml' => '7739',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature_laetizia.gif',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tHvis du vil vide mere, eller hvis du har sp&oslash;rgsm&aring;l, skal du f&oslash;lge <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>dette link.</b></a>\n",
		'ptext' =>"\tHvis du vil vide mere, eller hvis du har spørgsmål, skal du følge \n\tLink: [EMV LINK]4[EMV /LINK] \n\n"
	),
	//verifié
	'es_laetizia' => array(
		'url' => 'http://www.laetizia-a.com',
		'nom' => 'Laétizia',
		'folder' => 'es_laetizia',
		'ratioText' => '18737',
		'ratioHtml' => '18736',
		'emvsendertxt' => '16207',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '15690',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '16206',
		'emvSenderhtml2' => '',
		'emvImage' =>'11746',
		'emvDesFaqhtml' => '15507',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '15686',
		'emvchqhtml' => '15706',
		'phtml' => "\t\t\t\tPara más información o si tiene preguntas, por favor siga <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>este enlace.</b></a>\n",
		'ptext' =>"\tPara más información o si tiene preguntas, por favor siga\n\teste enlace.: [EMV LINK]4[EMV /LINK] \n\n"
	),
	//verifié	
	'cl_laetizia' => array(
		'url' => 'http://www.laetizia-ch.com',
		'nom' => 'Laétizia',
		'folder' => 'es_laetizia',
		'ratioText' => '3586',
		'ratioHtml' => '3582',
		'emvsendertxt' => '1592',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '1592',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '1591',
		'emvSenderhtml2' => '',
		'emvImage' =>'1590',
		'emvDesFaqhtml' => '3581',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '15686',
		'emvchqhtml' => '15706',
		'phtml' => "\t\t\t\tPara más información o si tiene preguntas, por favor siga <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>este enlace.</b></a>\n",
		'ptext' =>"\tPara más información o si tiene preguntas, por favor siga\n\teste enlace.: [EMV LINK]4[EMV /LINK] \n\n"
	),	//verifié	
	'ar_laetizia' => array(
		'url' => 'http://www.laetizia-ag.com',
		'nom' => 'Laétizia',
		'folder' => 'es_laetizia',
		'ratioText' => '3531',
		'ratioHtml' => '3530',
		'emvsendertxt' => '1587',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '3446',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '1584',
		'emvSenderhtml2' => '',
		'emvImage' =>'3902',
		'emvDesFaqhtml' => '3454',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '15686',
		'emvchqhtml' => '15706',
		'phtml' => "\t\t\t\tPara más información o si tiene preguntas, por favor siga <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>este enlace.</b></a>\n",
		'ptext' =>"\tPara más información o si tiene preguntas, por favor siga\n\teste enlace.: [EMV LINK]4[EMV /LINK] \n\n"
	),
	//verifié
	'in_laetizia' => array(
		'url' => 'http://www.laeya-m.com',
		'nom' => 'Laetizia',
		'folder' => 'in_laetizia',
		'ratioText' => '8717',
		'ratioHtml' => '3377',
		'emvsendertxt' => '565',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '562',
		'emvSenderhtml2' => '',
		'emvSenderhtml3' => '',
		'emvSenderhtml4' => '',
		'emvImage' =>'569',
		'emvDesFaqhtml' => '41699',
		'emvDesFaqhtml2' => '',
		'emvchq' => '',
		'imgname' => 'images_gen/signature_laetizia.gif',
		'emvsignature' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tFor any questions, please send an email to <br /> <a href='[EMV LINK]4[EMV /LINK]'><b>Link.</b></a>\n",
		'ptext' =>"\tFor any questions, please send an email to : [EMV LINK]4[EMV /LINK] \n\n"
	),		//verifié
	'ie_laetizia' => array(
		'url' => 'http://www.laetizia-ie.com',
		'nom' => 'Laetizia',
		'folder' => 'in_laetizia',
		'ratioText' => '',
		'ratioHtml' => '3368',
		'emvsendertxt' => '1613',
		'emvsendertxt2' => '1614',
		'emvDesFaqtxt' => '15690',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '1615',
		'emvSenderhtml2' => '1661',
		'emvImage' =>'1616',
		'emvDesFaqhtml' => '1072442',
		'emvDesFaqhtml2' => '',
		'emvchq' => '',
		'imgname' => 'images_gen/signature_laetizia.gif',
		'emvsignature' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tFor any questions, please send an email to <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>Link.</b></a>\n",
		'ptext' =>"\tFor any questions, please send an email to\n\tLink.: [EMV LINK]4[EMV /LINK] \n\n"
	),
	//verifié
	'it_laetizia' => array(
		'url' => 'http://www.laetizia-it.com',
		'nom' => 'Laetizia',
		'folder' => 'it_laetizia',
		'ratioText' => '3290',
		'ratioHtml' => '3289',
		'emvsendertxt' => '1152',
		'emvsendertxt2' => '1151',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		//'emvSenderhtml' => '3285',
		'emvSenderhtml' => '421',
		'emvSenderhtml2' => '',
		// 'emvImage' =>'1424',
		'emvImage' =>'422',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tPer maggiori informazioni o se avete delle domande, seguite <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>questo link.</b></a>\n",
		'ptext' =>"\tPer maggiori informazioni o se avete delle domande, seguite \n\tquesto link.: [EMV LINK]4[EMV /LINK]\n\n"
	),
	//verifié

	'nl_laetizia' => array(
		'url' => 'http://www.laetizia-nl.com',
		'nom' => '[EMV INCLUDE]2942[EMV /INCLUDE]',
		'folder' => 'nl_laetizia',
		'ratioText' => '3387',
		'ratioHtml' => '3386',
		'emvsendertxt' => '662',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '661',
		'emvSenderhtml2' => '',
		'emvImage' =>'372',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.gif',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\tVoor meer informatie of als u vragen hebt, volg dan <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>die link.</b></a>\n",
		'ptext' =>"\tVoor meer informatie of als u vragen hebt, volg dan  \n\tdie link.: [EMV LINK]4[EMV /LINK]\n\n"
	),
	//verifié
	'no_laetizia' => array(
		'url' => 'http://www.laetizia-no.com',
		'nom' => 'Laetizia',
		'folder' => 'no_laetizia',
		'ratioText' => '8756',
		'ratioHtml' => '3292',
		'emvsendertxt' => '1418',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '1415',
		'emvSenderhtml2' => '',
		'emvImage' =>'520',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature_laetizia.gif',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\t[EMV INCLUDE]515[EMV /INCLUDE]  <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'> <b>[EMV INCLUDE]516[EMV /INCLUDE]</b></a>\n",
		'ptext' =>"\t[EMV INCLUDE]515[EMV /INCLUDE] \n\t Linken.:  [EMV LINK]4[EMV /LINK]\n\n"
	),
	//verifié
	'pt_laetizia' => array(
		'url' => 'http://www.laetizia-v.com',
		'nom' => 'Laetizia',
		'folder' => 'pt_laetizia',
		'ratioText' => '',
		'ratioHtml' => '18735',
		'emvsendertxt' => '15727',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '15726',
		'emvSenderhtml2' => '',
		'emvImage' =>'11526',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '15730',
		'emvchqhtml' => '15731',
		'phtml' => "\t\t\t\t[EMV INCLUDE]16147[EMV /INCLUDE] <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'> <b>[EMV INCLUDE]16148[EMV /INCLUDE]</b></a>\n",
		'ptext' =>"\tPara mais informações ou tiver dúvidas, siga  \n\teste link: [EMV LINK]4[EMV /LINK]\n\n"
	),

	//vierifié

	'br_laetizia' => array(
		'url' => ' http://www.laetizia-br.com',
		'nom' => 'Laetizia',
		'folder' => 'pt_laetizia',
		'ratioText' => '',
		'ratioHtml' => '3291',
		'emvsendertxt' => '3043',
		'emvsendertxt2' => '3042',
		'emvSenderhtml' => '1608',
		'emvSenderhtml2' => '1609',
		'emvImage' =>'1558',
		'emvDesFaqtxt' => '3293',
		'emvDesFaqtxt2' => '3043',
		'emvDesFaqtxt3' => '3042',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\t[EMV INCLUDE]1605[EMV /INCLUDE] <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'> <b>[EMV INCLUDE]1606[EMV /INCLUDE]</b></a>\n",
		'ptext' =>"\tPara mais informações ou tiver dúvidas, siga  \n\teste link: [EMV LINK]4[EMV /LINK]\n\n"
	),

	//*****util
	'se_laetizia' => array(
		'url' => 'http://www.laetizia-se.com',
		'nom' => 'Laetizia',
		'folder' => 'se_laetizia',
        'ratioText' => '3314',		
        'ratioHtml' => '3315',
		'emvsendertxt' => '1452',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvsignature' => '',
		'emvSenderhtml' => '536',
		'emvSenderhtml2' => '',
		'emvImage' =>'537',
		'emvDesFaqhtml' => '538',
		'emvDesFaqhtml2' => '',
		'emvchq' => '',
		'imgname' => 'images_gen/signature_laetizia.gif',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tHvis du vil vide mere, eller hvis du har spørgsmål, skal du følge <br /> \n \t\t\t\t  <a href='[EMV LINK]4[EMV /LINK]'><b>dette link.</b></a> \n",
		'ptext' =>"\tHvis du vil vide mere, eller hvis du har spørgsmål, skal du følge \n\tLink: [EMV LINK]4[EMV /LINK]\n\n"
	),

	//verifié
	'fr_rmay' => array(
		'url' => 'http://www.r-may.com',
		'nom' => 'Mona Louisa',
		'folder' => 'fr_rmay',
		'ratioText' => '19250',
		'ratioHtml' => '19249',
		'emvsendertxt' => '11769',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '14972',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '11569',
		'emvSenderhtml2' => '',
		'emvImage' =>'1203',
		'emvDesFaqhtml' => '14971',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '10910',
		'emvchqhtml' => '10909',
		'phtml' => "\t\t\t\tPour plus d'informations ou si vous avez des questions, veuillez suivre <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>ce lien.</b></a>\n",
		'ptext' =>"\tPour plus d'informations ou si vous avez des questions, veuillez suivre \n\tce lien.: [EMV LINK]4[EMV /LINK]\n\n"
	),
	'dk_rmay' => array(
		'url' => 'http://www.r-maydk.com',
		'nom' => 'Mona Luisa',
		'folder' => 'dk_rmay',
		'ratioText' => '',
		'ratioHtml' => '4626',
		'emvsendertxt' => '2710',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '2708',
		'emvSenderhtml2' => '',
		'emvImage' =>'2264',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tPara mais informações ou tiver dúvidas, siga <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>dette link.</b></a>\n",
		'ptext' =>"\tHvis du vil vide mere, eller hvis du har spørgsmål, skal du følge \n\tLink: [EMV LINK]3[EMV /LINK] \n\n"
	),
	'no_ml' => array(
		'url' => 'http://www.r-mayno.com',
		'nom' => '[EMV INCLUDE]2945[EMV /INCLUDE]',
		'folder' => 'no_ml',
		'ratioText' => '4226', 
		'ratioHtml' => '4227',
		'emvsendertxt' => '3077',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '3079',
		'emvSenderhtml2' => '',
		'emvImage' =>'3076',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\t [EMV INCLUDE]3078[EMV /INCLUDE] \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>dette link.</b></a>\n",
		'ptext' => "\t [EMV INCLUDE]3078[EMV /INCLUDE] \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>dette link.</b></a>\n",
	),
	'ie_ml' => array(
		'url' => 'http://www.r-mayno.com',
		'nom' => 'Mona Luisa',
		'folder' => 'ie_ml',
		'ratioText' => '',
		'ratioHtml' => '',
		'emvsendertxt' => '',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '',
		'emvSenderhtml2' => '',
		'emvImage' =>'',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tFor any questions, please send an email to <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>Link.</b></a>\n",
		'ptext' =>"\tFor any questions, please send an email to\n\tLink.: [EMV LINK]4[EMV /LINK] \n\n"
	),
	'it_ml' => array(
		'url' => 'http://www.r-mayit.com',
		'nom' => 'Mona Luisa',
		'folder' => 'it_ml',
		'ratioText' => '4660',
		'ratioHtml' => '4661',
		'emvsendertxt' => '2764',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '2750',
		'emvSenderhtml2' => '',
		'emvImage' =>'2751',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tPer maggiori informazioni o se avete delle domande, seguite <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>questo link.</b></a>\n",
		'ptext' =>"\tPer maggiori informazioni o se avete delle domande, seguite \n\tquesto link.: [EMV LINK]4[EMV /LINK]\n\n"
	),
	//verifié
	'de_rmay' => array(
		'url' => 'http://www.rmayd.com',
		'nom' => 'Mona Luisa',
		'folder' => 'de_rmay',
		'ratioText' => '12542',
		'ratioHtml' => '12375',
		'emvsendertxt' => '10783',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '10782',
		'emvSenderhtml2' => '',
		'emvDesFaqtxt' => '12542',
		'emvDesFaqtxt2' => '10783',
		'emvImage' =>'83',
		'emvDesFaqhtml' => '12375',
		'emvDesFaqhtml2' => '10782',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.png',
		'emvchq' => '2601',
		'emvchqhtml' => '2602',
		'phtml' => "\t\t\t\tFür mehrere Informationen oder Wenn Sie Fragen haben,Folgen Sie bitte dieses <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>LINK.</b></a>\n",
		'ptext' =>"\tFür mehrere Informationen oder Wenn Sie Fragen haben, \n\tFolgen Sie bitte dieses LINK.: [EMV LINK]4[EMV /LINK]\n\n"
	),
	//verifié
	'es_rmay' => array(
		'url' => 'http://www.mluisa-e.com',
		'nom' => 'Mona Luisa',
		'folder' => 'es_rmay',
		'ratioText' => '23984',
		'ratioHtml' => '23985',
		'emvsendertxt' => '19141',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '18420',
		'emvSenderhtml2' => '',
		'emvImage' =>'4221',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '19100',
		'emvchqhtml' => '19120',
		'phtml' => "\t\t\t\tPara m&aacute;s informaci&oacute;n o si tiene preguntas, por favor siga<br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>este enlace.</b></a>\n",
		'ptext' =>"\tPara más información o si tiene preguntas, por favor siga \n\teste enlace.: [EMV LINK]4[EMV /LINK]\n\n"
	),
	'gr_laetizia' => array(
		'url' => 'http://www.laetizia-gr.com',
		'nom' => 'Laetizia',
		'folder' => 'gr_laetizia',
		'ratioText' => '7950',
		'ratioHtml' => '7946',
		'emvsendertxt' => '8374',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '8374',
		'emvSenderhtml2' => '',
		'emvImage' =>'3300',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'ct_images/signature_laetizia.gif',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tΓια περισσότερες πληροφορίες ή για οποιοδήποτε ερώτημα, παρακαλούμε<br />ακολουθήστε αυτόν<br />  \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>τον σύνδεσμο.</b></a>\n",
		'ptext' =>"\tΓια περισσότερες πληροφορίες ή για οποιοδήποτε ερώτημα, παρακαλούμε \n ακολουθήστε αυτόν \n\τον σύνδεσμο.: [EMV LINK]4[EMV /LINK]\n\n"
	),
	'ru_laetizia' => array(
		'url' => '',
		'nom' => 'Mona Luisa',
		'folder' => 'ru_laetizia',
		'ratioText' => '',
		'ratioHtml' => '',
		'emvsendertxt' => '',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '',
		'emvSenderhtml2' => '',
		'emvImage' =>'',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => '',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tPara m&aacute;s informaci&oacute;n o si tiene preguntas, por favor siga<br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>este enlace.</b></a>\n",
		'ptext' =>"\tPara más información o si tiene preguntas, por favor siga \n\teste enlace.: [EMV LINK]4[EMV /LINK]\n\n"
	),
	'se_rmay' => array(
		'url' => 'http://www.r-mayse.com',
		'nom' => 'Mona Luisa',
		'folder' => 'se_rmay',
		'ratioText' => '4866',
		'ratioHtml' => '4867',
		'emvsendertxt' => '8075',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '8074',
		'emvSenderhtml2' => '',
		'emvImage' =>'3109',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tHvis du vil vide mere, eller hvis du har spørgsmål, skal du følge <br /> \n \t\t\t\t  <a href='[EMV LINK]4[EMV /LINK]'><b>dette link.</b></a> \n",
		'ptext' =>"\tHvis du vil vide mere, eller hvis du har spørgsmål, skal du følge \n\tLink: [EMV LINK]4[EMV /LINK]\n\n"
	),

	'nl_rmay' => array(
		'url' => 'http://www.mluisa-n.com',
		'nom' => 'Mona Luisa',
		'folder' => 'nl_rmay',
		'ratioText' => '7182',
		'ratioHtml' => '7181',
		'emvsendertxt' => '3285',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '1425',
		'emvSenderhtml2' => '',
		'emvImage' =>'1424',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '2601',
		'emvchqhtml' => '2602',
		'phtml' => "\t\t\t\tVoor meer informatie of als u vragen hebt, volg dan <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>deze link.</b></a>\n",
		'ptext' =>"\tVoor meer informatie of als u vragen hebt, volg dan deze link : \n\t[EMV LINK]4[EMV /LINK]\n\n"
	),
	'cl_rmay' => array(
		'url' => 'http://www.mluisa-n.com',
		'nom' => 'Mona Luisa',
		'folder' => 'cl_rmay',
		'ratioText' => '',
		'ratioHtml' => '',
		'emvsendertxt' => '',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '',
		'emvSenderhtml2' => '',
		'emvImage' =>'',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '2601',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tVoor meer informatie of als u vragen hebt, volg dan <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>deze link.</b></a>\n",
		'ptext' =>"\tVoor meer informatie of als u vragen hebt, volg dan deze link : \n\t[EMV LINK]4[EMV /LINK]\n\n"
	),
	//verifié

	'br_rmay' => array(
		'url' => 'http://www.r-may-br.com',
		'nom' => 'Mona Luisa',
		'folder' => 'pt_rmay',
		'ratioText' => '',		
		'ratioHtml' => '3380',
		'emvsendertxt' => '1551',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '1553',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '1554',
		'emvSenderhtml2' => '',
		'emvImage' =>'3271',
		'emvDesFaqhtml' => '3380',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '10909',
		'emvchqhtml' => '10910',
		'phtml' => "\t\t\t\t[EMV INCLUDE]1556[EMV /INCLUDE] <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>este link</b></a>\n",
		'ptext' =>"\t[EMV INCLUDE]1556[EMV /INCLUDE] \n\t: [EMV LINK]4[EMV /LINK]\n\n"
	),
	'pt_rmay' => array(
		'url' => 'http://www.mluisa-b.com',
		'nom' => 'Mona Luisa',
		'folder' => 'pt_rmay',
		'ratioText' => '',		
		'ratioHtml' => '24468',
		'emvsendertxt' => '22367',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '20164',
		'emvSenderhtml2' => '',
		'emvImage' =>'10545',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '10909',
		'emvchqhtml' => '10910',
		'phtml' => "\t\t\t\t[EMV INCLUDE]22605[EMV /INCLUDE] <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>[EMV INCLUDE]20167[EMV /INCLUDE]</b></a>\n",
		'ptext' =>"\t[EMV INCLUDE]22604[EMV /INCLUDE] \n\t: [EMV LINK]4[EMV /LINK]\n\n"
	),
	'tr_rmay' => array(
		'url' => 'http://www.r-maytr.com',
		'nom' => 'Mona Luisa',
		'folder' => 'tr_rmay',
		'ratioText' => '',
		'ratioHtml' => '3287',
		'emvsendertxt' => '368',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '367',
		'emvSenderhtml2' => '',
		'emvImage' =>'366',
		'emvDesFaqhtml' => '370',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\t[EMV INCLUDE]371[EMV /INCLUDE]<br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>[EMV INCLUDE]621[EMV /INCLUDE]  [EMV INCLUDE]675[EMV /INCLUDE]</b></a>\n",
		'ptext' =>"\t[EMV INCLUDE]621[EMV /INCLUDE] \n\t[EMV INCLUDE]675[EMV /INCLUDE]: [EMV LINK]4[EMV /LINK]\n\n"
	),
	'pl_rmay' => array(
		'url' => 'http://www.r-maypl.com',
		'nom' => 'Mona Luisa',
		'folder' => 'pl_rmay',
		'emvsendertxt' => '4224',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '4223',
		'emvSenderhtml2' => '',
		'emvImage' =>'2356',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tAby uzyskać więcej informacji lub masz pytania, proszę na<br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>ten link.</b></a>\n",
		'ptext' =>"\tAby uzyskać więcej informacji lub masz pytania, proszę na ten link.:\n\t[EMV LINK]4[EMV /LINK]\n\n"
	),	

	//verified
	'de_theodor' => array(
		'url' => 'http://www.de-theo.com',
		'nom' => 'Theodor',
		'folder' => 'de_theodor',
		'ratioText' => '25011',
		'ratioHtml' => '25010',
		'emvsendertxt' => '21503',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '24554',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '21502',
		'emvSenderhtml2' => '',
		'emvImage' =>'4470',
		'emvDesFaqhtml' => '24553',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '4475',
		'emvchqhtml' => '4477',
		'phtml' => "\t\t\t\tFür mehrere Informationen oder Wenn Sie Fragen haben,Folgen Sie bitte dieses<br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>LINK.</b></a>\n",
		'ptext' =>"\tFür mehrere Informationen oder Wenn Sie Fragen haben, \n\tFolgen Sie bitte dieses LINK.:[EMV LINK]4[EMV /LINK]\n\n"
	),



	// 'br_rucker' => array(
	// 	'url' => 'http://www.theo-r.com',
	// 	'nom' => 'br_rucker',
	// 	'folder' => 'de_theodor',
	// 	'emvsendertxt' => '20407',
	// 	'emvsendertxt2' => '',
	// 	'emvDesFaqtxt' => '20406',
	// 	'emvDesFaqtxt2' => '',
	// 	'emvSenderhtml' => '20402',
	// 	'emvSenderhtml2' => '',
	// 	'emvImage' =>'4470',
	// 	'emvDesFaqhtml' => '20405',
	// 	'emvDesFaqhtml2' => '',
	// 	'emvsignature' => '',
	// 	'imgname' => 'images_gen/signature.jpg',
	// 	'emvchq' => '4475',
	// 	'emvchqhtml' => '4477',
	// 	'phtml' => "\t\t\t\tFür mehrere Informationen oder Wenn Sie Fragen haben<br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>[EMV INCLUDE]621[EMV /INCLUDE]  [EMV INCLUDE]675[EMV /INCLUDE]</b></a>\n",
	// 	'ptext' =>"\tFür mehrere Informationen oder Wenn Sie Fragen haben, \n\tFolgen Sie bitte dieses LINK.:[EMV LINK]4[EMV /LINK]\n\n"
	// ),


	//theodor fid_fr
	'fr_rucker' => array(
		'url' => 'http://www.ac-ruck.com',
		'nom' => 'Théodor',
		'folder' => 'rucker',
		'ratioText' => '25012',
		'ratioHtml' => '25013',
		'emvsendertxt' => '9711',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '9708',
		'emvSenderhtml2' => '',
		'emvImage' =>'2823',
		'emvDesFaqhtml' => '9709',
		'emvDesFaqhtml2' => '9712',
		'emvDesFaqtxt' => '9710',
		'emvDesFaqtxt2' => '5790',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.jpg',
		'emvchq' => '5323',
		'emvchqhtml' => '5322',
		'phtml' => "\t\t\t\tPour plus d'informations ou si vous avez des questions, veuillez suivre <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>ce lien.</b></a>\n",
		'ptext' =>"\tPour plus d'informations ou si vous avez des questions, veuillez \n\tsuivre ce lien.: [EMV LINK]4[EMV /LINK]\n\n"
	),
	'fr_rucker_acq' => array(
		'url' => 'http://www.ruckf.com',
		'nom' => 'Théodor',
		'folder' => 'rucker',
		'ratioText' => '62447',
		'ratioHtml' => '62448',
		'emvsendertxt' => '55766',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '55763',
		'emvSenderhtml2' => '',
		'emvImage' =>'34622',
		'emvDesFaqhtml' => '55764',
		'emvDesFaqhtml2' => '53530',
		'emvDesFaqtxt' => '55765',
		'emvDesFaqtxt2' => '53532',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.gif',
		'emvchq' => '52882',
		'emvchqhtml' => '52874',
		'phtml' => "\t\t\t\tPour plus d'informations ou si vous avez des questions, veuillez suivre <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>ce lien.</b></a>\n",
		'ptext' =>"\tPour plus d'informations ou si vous avez des questions, veuillez \n\tsuivre ce lien.: [EMV LINK]4[EMV /LINK]\n\n"
	),


	//verified


	'en_alisha' => array(
		'url' => 'http://www.ali-in.com',
		'nom' => 'Alisha',
		'folder' => 'en_alisha',
		'ratioText' => '',
		'ratioHtml' => '12381',
		'emvsendertxt' => '13613',
		'emvsendertxt2' => '',
		'emvsendertxt3' => '',
		'emvDesFaqtxt' => '13614',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '13611',
		'emvSenderhtml2' => '',
		'emvImage' =>'489',
		'emvDesFaqhtml' => '13612',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/img_signature.gif',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tFor any questions, please send an email to <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>Link.</b></a>\n",
		'ptext' =>"\tFor any questions, please send an email to \n\tLink.: [EMV LINK]4[EMV /LINK]\n\n"
	),
	//verified
	//Aasha dfid us
	'en_aasha' => array(
		'url' => 'http://www.aasha-f.com',
		'nom' => 'Aasha',
		'folder' => 'en_aasha',
		'ratioText' => '',
		'ratioHtml' => '1000010207',
		'emvsendertxt' => '1000008448',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '1000008368',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '1000010530',
		'emvSenderhtml2' => '',
		'emvImage' =>'1000005109',
		'emvDesFaqhtml' => '1000010531',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature_aasha.gif',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tFor any questions to Aasha, please send an email to <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>Link.</b></a>\n",
		'ptext' =>"\tFor any questions to Aasha, please send an email to \n\tLink.: [EMV LINK]4[EMV /LINK]\n\n"
	),	
	'en_aasha_in' => array(
		'url' => 'http://www.aasha-in.com',
		'nom' => 'Aasha',
		'folder' => 'en_aasha',
		'ratioText' => '',
		'ratioHtml' => '7035',
		'emvsendertxt' => '9116',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '1270',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '9110',
		'emvSenderhtml2' => '',
		'emvImage' =>'1268',
		'emvDesFaqhtml' => '9111',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature_aasha.gif',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tअधिक जानकारी के लिए अथवा किसी प्रश्न का उत्तर पाने के लिए कृपया इस <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b> लिंक पर जायें।</b></a>\n",
		'ptext' =>"\tअधिक जानकारी के लिए अथवा किसी प्रश्न का उत्तर पाने के लिए कृपया इस लिंक पर जायें।:  [EMV LINK]4[EMV /LINK]\n\n"
	),
	
	
	'en_aasha_acq' => array(
		'url' => 'http://www.aasha-online.com',
		'nom' => 'Aasha',
		'folder' => 'en_aasha',
		'ratioText' => '',
		'ratioHtml' => '63621',
		'emvsendertxt' => '58542',
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '58364',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '223481',
		'emvSenderhtml2' => '',
		'emvImage' =>'44104',
		'emvDesFaqhtml' => '223483',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature_aasha.gif',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tFor any questions to Aasha, please send an email to <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>Link.</b></a>\n",
		'ptext' =>"\tFor any questions to Aasha, please send an email to \n\tLink.: [EMV LINK]4[EMV /LINK]\n\n"
	),
	'tr_laetizia' => array(
		'url' => 'http://www.laet-tr.com',
		'nom' => 'Laetizia',
		'folder' => 'tr_laetizia',
		'ratioHtml' => '7347',
		'ratioText' => '',
		'emvsendertxt' => '4650',	
		'emvsendertxt2' => '',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvSenderhtml' => '3739',
		'emvSenderhtml2' => '',
		'emvImage' =>'3740',
		'emvDesFaqhtml' => '3742',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature_Laetizia.gif',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\t[EMV INCLUDE]4649[EMV /INCLUDE]<br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>[EMV INCLUDE]4654[EMV /INCLUDE]  [EMV INCLUDE]4655[EMV /INCLUDE]</b></a>\n",
		'ptext' =>"\t[EMV INCLUDE]4654[EMV /INCLUDE] \n\t[EMV INCLUDE]4655[EMV /INCLUDE]: [EMV LINK]4[EMV /LINK]\n\n"
	),
	'fr_myrian' => array(
		'url' => 'http://www.rin-fr.com',
		'nom' => 'Rinalda',
		'folder' => 'fr_myriana',
		'ratioText' => '',
		'ratioHtml' => '1083087',
		'emvsendertxt' => '1072986',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '1072985',
		'emvSenderhtml2' => '',
		'emvImage' => '1045962',
		'emvDesFaqtxt' => '1073002',
		'emvDesFaqtxt2' => '',
		'emvDesFaqhtml' => '1072442',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.gif',
		'emvchq' => '1072984',
		'emvchqhtml' => '1072983',
		'phtml' => "\t\t\t\tPour plus d'informations ou si vous avez des questions, veuillez suivre <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>ce lien.</b></a>\n",
		'ptext' =>"\tPour plus d'informations ou si vous avez des questions, veuillez \n\tsuivre ce lien.: [EMV LINK]4[EMV /LINK] \n\n"
	),
	
		'fi_laetizia' => array(
		'url' => 'http://www.laetizia-fi.com',
		'nom' => 'Laetizia',
		'folder' => 'fi_laetizia',
		'ratioText' => '7985',
		'ratioHtml' => '5128',
		'emvsendertxt' => '5125',
		'emvsendertxt2' => '',
		'emvSenderhtml' => '5122',
		'emvSenderhtml2' => '',
		'emvImage' => '5121',
		'emvDesFaqtxt' => '',
		'emvDesFaqtxt2' => '',
		'emvDesFaqhtml' => '',
		'emvDesFaqhtml2' => '',
		'emvsignature' => '',
		'imgname' => 'images_gen/signature.gif',
		'emvchq' => '',
		'emvchqhtml' => '',
		'phtml' => "\t\t\t\tJos haluat lisätietoja tai sinulla on kysymyksiä, napsauta <br /> \n \t\t\t\t <a href='[EMV LINK]4[EMV /LINK]'><b>tätä linkkiä.</b></a>\n",
		'ptext' =>"\tJos haluat lisätietoja tai sinulla on kysymyksiä, napsauta \n\ttätä linkkiä: [EMV LINK]4[EMV /LINK] \n\n"
	)

);



